import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { pool } from './pool.js';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const sql = await fs.readFile(path.join(__dirname, 'sql', '001_init_ashenbastion.sql'), 'utf8');
await pool.query(sql);
console.log('Migration applied');
await pool.end();
